name: 'NumenActions Publish'
description: 'Build and Push Container to registry'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/fiveateooate/numenactions:latest'
  entrypoint: '/usr/local/bin/numencli'
  args:
    - --loglevel
    - debug
    - publish

