name: 'NumenActions Publish'
description: 'Build and Push Container to registry'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/usr/local/bin/publish'
  args:
    - --loglevel
    - debug
