#!/usr/bin/env python3

import argparse
import os

from numenactions import logger_setup


def main():
    parser = argparse.ArgumentParser(description="NumenActions - They can do anything!")
    parser.add_argument(
        "--loglevel", help="log level", default=os.environ.get("LOGLEVEL")
    )
    args = parser.parse_args()
    logger = logger_setup("numenactions", args.loglevel)

    logger.debug("runing publish action")


if __name__ == "__main__":
    main()
