#!/usr/bin/env python3

import argparse
import os

import numenactions


def main():
    parser = argparse.ArgumentParser(description="NumenActions - They can do anything!")
    parser.add_argument(
        "--loglevel", help="log level", default=os.environ.get("LOGLEVEL")
    )
    args = parser.parse_args()
    logger = numenactions.logging.logger_setup("numenactions", args.loglevel)

    logger.debug("runing changetype action")
    ct = numenactions.changetype.ChangeType()
    change = ct.changetype()
    logger.debug(f"changetype: {change}")
    eh = numenactions.envhelper.EnvHelper()
    eh.set_github_env("NUMEN_CHANGE_TYPE", change)


if __name__ == "__main__":
    main()
